detectors:
  IrresponsibleModule:
    enabled: false
  UncommunicativeModuleName:
    accept:
      - V1
      - V2

directories:
  "app/controllers":
    UnusedPrivateMethod:
      enabled: false
    InstanceVariableAssumption:
      enabled: false
  "app/helpers":
    IrresponsibleModule:
      enabled: false
    UtilityFunction:
      enabled: false
  "app/mailers":
    InstanceVariableAssumption:
      enabled: false
  "app/models":
    InstanceVariableAssumption:
      enabled: false
  "app/workers":
    UtilityFunction:
      enabled: false
  "spec/mailers/previews":
    UtilityFunction:
      enabled: false
